### PR TITLE
Constrain BaseController state to be valid JSON

### PR DESCRIPTION
**Pull request by Gudahtt**
The BaseController state is now constrained to valid JSON. Anything that can't be serialized (e.g. functions) or gets mutated during
serialization (e.g. `undefined` gets converted to `null`) is disallowed.

This should prevent an entire class of bugs resulting from unexpected changes when serializing state as JSON. For example, we serialize state when sending it over `postMessage`, and when persisting the state.

### CODE REVIEW

**Comment by Gudahtt** [comment]
Depends upon #365

**Comment by Gudahtt** [comment]
Note that I haven't added any test cases for this type, as testing that types work properly can be a bit challenging. But the comment I got this type from did include [a TypeScript playground link will a comprehensive set of tests](https://www.typescriptlang.org/play?#code/C4TwDgpgBGBOCWBbex4DdoF4oDsCuANgQLABQUFUAPlAEYD29BEAhjmZdbnorRLB0o0AzsAQ4A5mTKhIUACIQAZvBwoIBEADl6wAFLD6OFrWZRsACgsBKcwD4obELZp4cAE2WqI76aVnQAJLCBkYmzAA8ACoOmIIUAPQJUADCABYQAMYA1lDwSlDAGbDQLCWOOCC4RgC0AFaGxqbQAcJQJXAQwhA4wD55OIUZUG7wRvFQSVA6fQBcI91Q9AXAeGDMbapD8G0qsKJQmUbuKGODwvCeNaIQYG0nogi0eKgYh8enYQSF4F0TUxZutA0sBgHdZkkJCg0nhaAA6I6IBLITKweiGJTABJRX4AZVR8DAWJ2wjwXQSACYAJwAZgAbAAOADEJLJiMQPWANQALABWGm86n8inWCYAbQAogAPMQsTLAaIAGgUXjUfU0M1CTWYdgAulAIDKeu42mKcBAMLBdRNOFMdDh6o1wi1fiM1EYoAB3Fi7ehudwGxBEkA2ygAfigUQNRo8bTgSFOGFDnESyQACghkK9oDtHJlMrdgM7kymI1ES7bkgB5Ir8T07aCZDI5PIFMqwFgh8gpnvzKOGvqxqAWVRKfhQACq1jF1u7Pfnk2SAEFYB2QG0ytBhJBMvAWAQANxQOp4A5NrK5dudg3MDm9H6QCvziPBLXOiITuwzp89qY14r1os54tvkSy0HUWTAD+KZ9tGg4mmBEHytBC5TIEwAAOQboM9DgZBKHPlAADeBELqmUDofwLB9EslpQNkEDrgMiGQYcPoQKRZFimmzEMSAyyRrqsycWRlBTAASlkeD7Ogjb7t8Sj0LAhxpPABDuCU7BzqJOmcK+TrNNE3G6nYImUAAvmZ5H-nWDYVFUujFNUDq4UhwDVHQZI4PQVlQPM5qWiWf61rAgHQN5DoNGEzQPtAowet6vr+tU7kQEGoAlv5Fr8H4ShuPKZyFF0CoxBYUU4PM+nRZEMTWPMaD0JcxGCFMUTFXkmyDLW7xBmp1FnGQlmkGQqh9LAShytAS7Nd2LD+TwfCwAeg1+JkBA+m0ABCM0UCwACE828Pwy2kENI29PwE0FlAABqO2OGGh2LSdZ2kKNl2TVAAAa91zQo1EQC9fjveNn0AJq-Y9-19EDw1vRdoPXQAWr9T3jq4Hiqj4sPnWNV3QAA6pD8w2PY9k46QRw4AcTjmNwRCONhIAnWQUyImAanjlWADSMjFRY+BENYJ19KIFgTQQ3TC3zYsAAzS-4-MAERKwrovABYM5q-zRHmdrYtirLur6xrRGOPMstQHrIv87TPpQEuJsWHbW1O2bf1m7Q8xiGSyqZPMuvmcq7jzGKuvKhSypK6pSu6tbMsa2HQfEX90fwEryeCwQyo0sbLOkGz9C9cwylFGinrCAnAsQJ60MQDYTtmjXdc2HnVfu1ltfyADpPx4rYsu7dTuD19w+VIzUBg2PVT20j08TwTTv+lj7iiv3Gu8hP+BHcpGOeCo5qrydQA).

I had intended to look into something like [`tsd`](https://github.com/SamVerschueren/tsd) later on to test our types.

**Review by brad-decker — APPROVED** [review]
LGTM! Dope!

**Comment by brad-decker** [comment]
that type is ingenious.

**Pull request merged**
