### PR TITLE
Add options to GasFeeController fetchGasFeeEstimates

### PR DESCRIPTION
**Pull request by wachunei**
This PR adds an `options` object to `fetchGasFeeEstimates` and `_fetchGasFeeEstimateData`. Options include `shouldUpdateState: boolean` property to decide wether to update state or not, `true` by default.

### CODE REVIEW

**Review by brad-decker — APPROVED** [review]

**Comment by Gudahtt** [comment]
What is this for? I can't think of a situation where you'd want to keep the gas estimate data stale on purpose.

**Comment by wachunei** [comment]
SwapsController needs estimate data every polling cycle, which is every ~45 seconds (or the value the quotes come with). At the same time GasFeeController is polling an updating its state, so there's a case the estimate data from the GasFeeController is updated when fetching the next SwapsController state, even if the current polling cycle from GasFeeController has not finished, and when it finishes it will update again.

This option is for SwapsController to fetch and set data to the state on the very first cycle only, from there on, GasFeeController will update its state with the polling.

**Comment by Gudahtt** [comment]
Right but what negative consequence are we trying to avoid by not updating the state with the new gas estimates? Would it be bad if the gas estimates were updated slightly sooner because of the swaps controller fetching updated estimates?

**Comment by wachunei** [comment]
The UI animates when the estimates update from the GasFeeController, this will result on the UI animating more than necessary.

**Comment by Gudahtt** [comment]
Huh, OK. Well... this seems less than ideal. I see why this might be the simplest solution for now though.

Back when the swaps UI was being discussed, I had thought the plan was to control the gas price change animation in the UI to ensure nothing janky happened like successive refreshes. I don't know how it was implemented after though. The UI does seem like the better place to handle that UI problem.

**Comment by brad-decker** [comment]
Any ideas on how we prevent a UI update from a state change that results in new values, sooner than expected? We can only prevent these animations if the underlying values don't change -- if they do there is no way to know if this occurred on a normal interval or because of a fetch like this, at least I don't think there is.

fWIW on mobile the animations are already being handled this way (triggered by an underlying value change)

**Comment by Gudahtt** [comment]
Sure, depend on what we want. e.g. if we want to prevent the value from changing twice within a 10 second window, we can cache the value in the UI and start a timer, then update the value base don state. Or if we want to prevent the gas price from changing within 10 seconds of the page loading, we can do that. Or both. Whatever design wants.

**Review by Gudahtt — APPROVED** [review]

**Pull request merged**
