### PR TITLE
v2.0.4

### PR DESCRIPTION
**Pull request by whymarrh**
This PR represents v2.0.4.

### CODE REVIEW

**Comment by Gudahtt** [comment]
Could also mention #252 🤔 Not sure what our standards are for what should be included in a library changelog.

**Comment by whymarrh** [comment]
Whoops, I can update the changelog again

**Comment by whymarrh** [comment]
> A new version of the package `@metamask/controllers` (2.0.4) was published at 2020-08-18T22:09:38.224Z from [redacted]. The shasum of this package was `7ea81cc1f3d864d9e745ecde3b47adbaa62724fd`.

**Comment by whymarrh** [comment]
I can't unpublish this one, oh well 🤷‍♂️ 

```
$ npm unpublish '@metamask/controllers@2.0.4'
npm ERR! code E405
npm ERR! 405 Method Not Allowed - PUT https://registry.npmjs.org/@metamask%2fcontrollers/-rev/6-8a7577caf8aa91d4c07fd963d3dae5b3 - You can no longer unpublish this package.
npm ERR! Failed criteria: 
npm ERR! has dependent packages in the registry
npm ERR! 
npm ERR! Please deprecate it instead:
npm ERR! npm deprecate -f '@metamask/controllers@2.0.4' "this package has been deprecated"
npm ERR! To learn more about our unpublish policies, see https://www.npmjs.com/policies/unpublish
```

**Pull request merged**
