### PR TITLE
[GasController] Check for undefined basefeePerGas

### PR DESCRIPTION
**Pull request by peak3d**
**PR Title**
GasController: Don't fall back to eth_gasPrice if node returns empty fee history

**Description**
go-ethereum based chains never return empty baseFeePerGas because this is omitted in the serializer:
```
type feeHistoryResult struct {
	OldestBlock  *hexutil.Big     `json:"oldestBlock"`
	Reward       [][]*hexutil.Big `json:"reward,omitempty"`
	BaseFee      []*hexutil.Big   `json:"baseFeePerGas,omitempty"` <---
	GasUsedRatio []float64        `json:"gasUsedRatio"`
}
```
Current code checks for `baseFeePerGas.length > 0` without checking for the occurence of this element.
This leads to an exception and in later flow to fallback to eth_gasPrice mode

- FIXED:
no feeMarket mode available in case one of past requests return no results

**Checklist**

- [X] Tests are included if applicable
- [X] Any added code is fully documented

**Issue**

### CODE REVIEW

**Comment by peak3d** [comment]
> Good catch! I tried to read the geth source code when implementing this file but I obviously didn't see this. Makes total sense though. Would you be willing to add tests for this?

done

**Comment by mcmire** [comment]
Looks like this is out of date, would you mind rebasing? Thanks.

**Review by mcmire — APPROVED** [review]
LGTM!

**Comment by mcmire** [comment]
@peak3d Apologies — do you mind rebasing this again? I will make sure to get this in today.

**Comment by peak3d** [comment]
> Apologies — do you mind rebasing this again? I will make sure to get this in today

NP, but I guess I'll have to rebase one of my two commits because they affect the same file.....
I'm CET timezone, so would be great if you merge at least one so I can care about the other....

**Pull request merged**
