### PR TITLE
Make TokenRatesController findChainSlug method accommodate hex formatted chainIds

### PR DESCRIPTION
**Pull request by adonesky1**
The findChainSlug method on the TokensRateController should accept and correctly search for chain slugs when passed either a hex or decimal formatted chainId.

- CHANGED:
  - Makes a hex formatted chainID a valid argument to the findChainSlug method on TokensRateController.

### CODE REVIEW

**Comment by adonesky1** [comment]
@danjm @Gudahtt I think this change may run the risk of a misidentified chain if say, a chain from the extension's network controller passed as the chainID in hex format that didn't start with '0x' and was a valid number that could be found in coingecko's platform list. All the instances I've seen coming from extension's network controller where this confusion could occur ( e.g. '0x38' = 56) are prefixed with '0x' but just want to raise this to your attention for thoughts.

**Comment by Gudahtt** [comment]
We should be guaranteeing that the chain ID in the network controller is always a hex-prefixed string. What motivated this change? Did you find an example of the network chain ID being a decimal string?

**Comment by wachunei** [comment]
FYI: When we created `swaps-controller` I wanted to add a util function to handle chain ids from all sort of inputs into a base 10 numeric string, but I was told it should not be done because Network Controller always handles that type, every case. It seems there's a major discrepancy with the extension's Networks Controller, which handles base 16 0x prefixed strings always. 

Swaps, Token Rates and Smart Transactions controllers are currently not handling the chain id and expecting base 10 numeric string.

**Comment by adonesky1** [comment]
@Gudahtt, yea so the reason is, as @wachunei alludes to, the controllers based NetworkController is actually [using base 10 numeric strings for chainId](https://github.com/MetaMask/controllers/blob/c7d7480339b9dc62bdd2a2b8cada49a96d62b01e/src/network/NetworkController.ts#L23), while the extensions NetworkController uses base 16 numeric strings.

**Comment by Gudahtt** [comment]
Huh, OK. That is a pretty major discrepancy. 

In the meantime we can accept one type or the other, and ensure the caller converts the chain ID accordingly. Accepting both would further entrench this ambiguity and could lead to parsing bugs.

**Comment by adonesky1** [comment]
@Gudahtt ok yeah that makes sense.

**Comment by adonesky1** [comment]
OBE - Extension modifies chainID to dec format before passing into TokenRatesController OnNetworkChange instead of this change.

**Pull request closed without merging**
