### PR TITLE
Reset polling onNetworkStateChange

### PR DESCRIPTION
**Pull request by rickycodes**
This is to deal with an edge case @danjm discovered where in the extension you can have a transaction in progress (which starts polling) and then if you switch network you're potentially getting the wrong quotes. This resets polling on network change if there's any polling already in progress.

### CODE REVIEW

**Review by danjm — APPROVED** [review]
LGTM

**Comment by Gudahtt** [comment]
What is this for?

**Comment by rickycodes** [comment]
@Gudahtt @danjm sorry i had meant to add desc. it's added now

**Review by Gudahtt — APPROVED** [review]
Thanks! LGTM

**Pull request merged**
