### PR TITLE
Expose WebSocket for network access

### PR DESCRIPTION
**Pull request by FrederikBolding**
Expose `WebSocket` for network access endowment.

**Description**

- ADDED:
  - Expose `WebSocket` for network access endowment.

**Checklist**

- [x] Tests are included if applicable
- [x] Any added code is fully documented

### CODE REVIEW

**Review by rekmarks — CHANGES_REQUESTED** [review]
So, since we're adding WebAssembly as a default endowment, we should get rid of the endowment permission for it. We should still add `XMLHttpRequest` to the network access endowment.

**Comment by FrederikBolding** [comment]
> So, since we're adding WebAssembly as a default endowment, we should get rid of the endowment permission for it. We should still add `XMLHttpRequest` to the network access endowment.

Done!

> _Edit:_ While we're here, it might be worth looking into whether we can add `WebSocket` as one of the available APIs.

The only issue with adding `WebSocket` is that it's not available for Node.js. So I'm guessing we'll need some sort of polyfill or otherwise create a shared interface 🤔

**Comment by FrederikBolding** [comment]
According to this implementation https://github.com/heineiuo/isomorphic-ws you can use the browser WebSocket and `ws` interchangeably in some cases, but not all.

> Some major differences:
> - no `Server` implementation in browsers
> - no support for the constructor [options](https://github.com/websockets/ws/blob/master/doc/ws.md#new-websocketaddress-protocols-options) argument in browsers

I guess we could strip out some of these things in the same way we do for WebAssembly? 🤔

**Review by rekmarks — APPROVED** [review]
LGTM!

**Review by rekmarks — CHANGES_REQUESTED** [review]
Wait, scratch that.

**Review by rekmarks — APPROVED** [review]
LGTM!

**Pull request merged**
