### PR TITLE
Fix update conversionDate return

### PR DESCRIPTION
**Pull request by igorms-cons**
**Update the conversionDate return *

- conversionDate value was always returned even when the fetch getPricingURL was failing (offline for example). Then, the extension is receiving the conversion date if there is no network. 
-  This issue is relate to https://github.com/MetaMask/metamask-extension/issues/10741. 

**FIXES:**  The purpose of this PR is to return a good timestamp if the fetch was a success otherwise null (like current conversionRate value )

**BREAKING:** Metamask extension now has to update the SettingsTab component. This is currently in progress in the PR https://github.com/MetaMask/metamask-extension/pull/12422

### CODE REVIEW

**Comment by mhasanagic** [comment]
Verified by QA

**Comment by igorms-cons** [comment]
Hey @Gudahtt ,

You 're understood what is happening here.  There was no particular reason on why I set to null  `conversionDate` if the fetch is failing. I copy the behaviour of `conversionRate`, which its set to null when failing. 

I can change this behaviour, use the state to always keep a value to `conversionDate` .
Let me know

**Comment by Gudahtt** [comment]
That's a good point. That was done for the case where we're switching currencies. We want to erase the old `conversionRate` in that case even if the request fails, because it's no longer applicable to the new currency. `converisonDate` is similarly obsolete after switching currencies, so using the same behavior makes sense.

The solution in this PR is an improvement, so I think it can be accepted as is. We should improve this further to distinguish the "update" case from the "switch currencies" case though. Ideally both the conversion rate and date would be preserved on failure for a regular update, but set to `null` after a switch.

**Comment by igorms-cons** [comment]
> We should improve this further to distinguish the "update" case from the "switch currencies" case though. Ideally both the conversion rate and date would be preserved on failure for a regular update, but set to `null` after a switch.

mmmh good point.
You want me to go further and implement  on this PR? or open a new ticket :)

**Comment by Gudahtt** [comment]
It would probably be easiest to merge this as-is and create a separate PR for that improvement, since this is already finished and ready to merge. I will approve it now.

**Review by Gudahtt — APPROVED** [review]
LGTM!

**Comment by igorms-cons** [comment]
great!

**Comment by igorms-cons** [comment]
@Gudahtt  quick question please. 
Do you when  will this version be linked to the repo extension develop branch?

**Comment by Gudahtt** [comment]
This change was included in the v19 release which was published yesterday, so it can be used in the extension now. We usually include controller updates in the first PR that needs the update, so I am uncertain when it will land. Feel free to include the update in https://github.com/MetaMask/metamask-extension/pull/12422

**Pull request merged**
