### PR TITLE
Expose getFormattedIpfsUrl

### PR DESCRIPTION
**Pull request by mcmire**
This function was previously available before the monorepo conversion under `src/util.ts` and has since been moved to `src/assetsUtil.ts` in `@metamask/assets-controllers`.

### CODE REVIEW

**Review by Gudahtt — APPROVED** [review]
LGTM!

**Comment by Gudahtt** [comment]
I have just audited the old `util` module to look for more examples like this of functions that used to be exposed, but are no longer. Here's what I found, organized by package:


transaction-controller:
====================
getEtherscanApiUrl
handleTransactionFetch
normalizeTransaction
validateTransaction
isEIP1559Transaction
getIncreasedPriceHex
getIncreasedPriceFromExisting
validateGasValues
isFeeMarketEIP1559Values
isGasPriceValue
validateMinimumIncrease

message-managers:
=====================
normalizeMessageData
validateSignMessageData
validateTypedSignMessageDataV1
validateTypedSignMessageDataV3

assets-controllers:
===================
validateTokenToWatch
removeIpfsProtocolPrefix
getIpfsCIDv1AndPath
addUrlProtocolPrefix
getFormattedIpfsUrl
SupportedTokenDetectionNetworks
isTokenDetectionSupportedForNetwork
isTokenListSupportedForNetwork

**Comment by Gudahtt** [comment]
We should probably either

1) Expose these methods for now, noting the change in the most relevant changelog(s), or
2) Note in relevant changelog(s) that these methods will no longer be exposed

**Comment by mcmire** [comment]
I did include this little blurb in the changelog for `controller-utils`:

> - `src/util.ts` (minus transaction-, assets-, and message manager-related functions)

But this is easily missed, and I think it would be better to list out exact the functions that were moved. I can do that.

**Pull request merged**
