### PR TITLE
re-enable preloaded testnet conversion rates

### PR DESCRIPTION
**Pull request by adonesky1**
Resolves https://github.com/MetaMask/metamask-extension/issues/14569

We recently [changed settings for preloaded testnets](https://github.com/MetaMask/metamask-extension/pull/14454) (Rinkeby, Ropsten, Goerli, Kovan) to prefix their ticker symbols with the testnet name. This led to our no longer fetching conversion rates for these testnets. This re-enables these conversion rates for the enumerated preloaded testnets.

### CODE REVIEW

**Comment by seaona** [comment]
@adonesky1 I cannot approve the PR as I believe I don't have access to this repo

**Review by seaona — APPROVED** [review]

**Review by mcmire — CHANGES_REQUESTED** [review]
Is there a test we can write for this to verify that this is doing the right thing?

**Comment by seaona** [comment]
@mcmire I was not sure how to test it neither. It's not exactly what you are asking but at Metamask level, I implemented an e2e test for verifying the functionality
https://github.com/MetaMask/metamask-extension/pull/14649

**Review by seaona — APPROVED** [review]

**Review by mcmire — APPROVED** [review]
Thanks for the update! This looks good to me.

**Review by seaona — APPROVED** [review]

**Pull request merged**
