### PR TITLE
[FIX] - Allow Optimism & Optimism Testnet to be added via wallet_addEthereumChain

### PR DESCRIPTION
**Pull request by sethkfman**
**PR Title**

Allow Optimism & Testnet to be added via `wallet_addEthereumChain`

**Description**

- Because optimism was added in the default network list the wallet_addEthereumChain method fails when adding Optimism or the Optimism Testnet. These networks were initially added to identify them as custom network but through further testing the Optimism network is a custom network since it gets added using the  `setupStandardProvider` method.

- FIXED:

  - This fixes the issue of adding Optimism using the wallet_addEthereumChain method.

- REMOVED:

  - Remove Optimism and the Optimism Testnet

**Checklist**

- [x] Tests are included if applicable
- [x] Any added code is fully documented

**Issue**

Resolves [4492](https://github.com/MetaMask/metamask-mobile/issues/4492)

### CODE REVIEW

**Review by blackdevelopa — APPROVED** [review]
LGTM. Removes Optimism and its testnet to be added via `wallet_addEthereumChain`. 

Test seem to be failing here. `src/transaction/TransactionController.test.ts:139:32 - error TS2339: Property 'optimism' does not exist on type 'typeof NetworksChainId'.`

**Review by mcmire — COMMENTED** [review]
This makes sense to me. That said, the type on line 46 of `src/constants.ts` doesn't seem right now, as the object doesn't include all of the properties of `NetworkType`, only a subset. I think we should fix that.

**Comment by Gudahtt** [comment]
@mcmire could you elaborate? It looks like `NetworkType` is an enum, so it doesn't have any properties. Every network type appears to be present in that constant as well. Maybe I'm missing something.

**Comment by mcmire** [comment]
@Gudahtt Oops, sorry, I might have been  looking at something else. That looks right to me after all.

**Review by mcmire — APPROVED** [review]
LGTM!

**Pull request merged**
