### PR TITLE
v11.1.0 release

### PR DESCRIPTION
**Pull request by brad-decker**
Proposed Changelog:

### Added
- Added GasFeeController to provide gas fee estimates [#494](https://github.com/MetaMask/controllers/pull/494)

### Changed
- Added chainId support to TokenRatesControllers [#476](https://github.com/MetaMask/controllers/pull/476)
- Added iconUrl to Token type in TokenListController [#512](https://github.com/MetaMask/controllers/pull/512)

### CODE REVIEW

**Comment by wachunei** [comment]
I think this should be `12`, because of this: https://github.com/MetaMask/controllers/pull/476#issuecomment-874134433, but mobile has not adopted 11 yet so we could make an exception perhaps? :unsure:

**Comment by brad-decker** [comment]
I'm fine making it v12 @Gudahtt do you have opinions?

**Comment by Gudahtt** [comment]
I agree with @wachunei ; this should be v12 because of the linked breaking change. Lets make the update as easy as possible by highlighting the required changes.

**Comment by brad-decker** [comment]
Closing in favor of #515

**Pull request closed without merging**
