### PR TITLE
Replace web3 with ethers.js

### LINKED ISSUE #108: remove the use of web3
better if we use https://github.com/ethjs/ethjs-contract and https://github.com/ethjs/ethjs-query

### PR DESCRIPTION
**Pull request by whymarrh**
Closes #108

This PR replaces our usages of web3 with [ethers.js](https://docs.ethers.io/ethers.js/html/). ethers.js features:

> - **Tiny** (~88kb compressed; 284kb uncompressed)
> - Large collection of **test cases** which are maintained and added to
> - Fully **TypeScript** ready, with definition files and full TypeScript source

It's also not web3.

### CODE REVIEW

**Comment by estebanmino** [comment]
@whymarrh please let us time to try this PR on mobile first before merging it, it could break things. I forgot to comment this.

**Comment by whymarrh** [comment]
Yeah no worries, this would go in 2.x, if anything 👍

**Comment by whymarrh** [comment]
This fixes the last advisory `yarn audit` produces:

```
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ low           │ Insecure Credential Storage                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ web3                                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ No patch available                                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ web3                                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ web3                                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://www.npmjs.com/advisories/877                         │
└───────────────┴──────────────────────────────────────────────────────────────┘
```

**Comment by whymarrh** [comment]
@rekmarks @estebanmino can y'all post here what's wrong with this PR on mobile

**Comment by whymarrh** [comment]
Closing this for now, it's a low priority

**Pull request closed without merging**
